<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-2AFDCIK" failures="1" tests="4" name="Sqrt Tests" time="0.0" errors="0" timestamp="28 июн. 2018 16:05:33 GMT">
  <testcase classname="com.epam.cdp.CalcUnitTests.Tests.SqrtCalcTestDouble" name="sqrtTest" time="0.0">
    <failure type="org.testng.TestException" message="
Method SqrtCalcTestDouble.sqrtTest()[pri:0, instance:com.epam.cdp.CalcUnitTests.Tests.SqrtCalcTestDouble@34f22f9d] should have thrown an exception of type class java.lang.Exception">
      <![CDATA[org.testng.TestException: 
Method SqrtCalcTestDouble.sqrtTest()[pri:0, instance:com.epam.cdp.CalcUnitTests.Tests.SqrtCalcTestDouble@34f22f9d] should have thrown an exception of type class java.lang.Exception
at Runners.CalcTestsRunner.main(CalcTestsRunner.java:27)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- sqrtTest -->
  <testcase classname="com.epam.cdp.CalcUnitTests.Tests.SqrtCalcTestDouble" name="sqrtTest" time="0.0"/>
  <testcase classname="com.epam.cdp.CalcUnitTests.Tests.SqrtCalcTestDouble" name="sqrtTest" time="0.0"/>
  <testcase classname="com.epam.cdp.CalcUnitTests.Tests.SqrtCalcTestDouble" name="sqrtTest" time="0.0"/>
</testsuite> <!-- Sqrt Tests -->
